/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    media: Media;
    projects: Project;
    skills: Skill;
    posts: Post;
    navigation: Navigation;
    leads: Lead;
    'tg-subscribers': TgSubscriber;
    services: Service;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'tg-subscribers': TgSubscribersSelect<false> | TgSubscribersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'team-page': TeamPage;
    'home-page': HomePage;
    footer: Footer;
  };
  globalsSelect: {
    'team-page': TeamPageSelect<false> | TeamPageSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Полное имя, отображается на сайте
   */
  name?: string | null;
  /**
   * Часть адреса страницы: /team/ivan-orlov. Латиница, цифры, дефисы.
   */
  slug?: string | null;
  isPublic?: boolean | null;
  role?: ('admin' | 'editor') | null;
  /**
   * Например: Ведущий Битрикс-разработчик
   */
  position?: string | null;
  craft?: ('dev' | 'design' | 'devops' | 'management' | 'analytics' | 'qa') | null;
  /**
   * Фото мастера. Рекомендуется квадратное, минимум 400×400 px.
   */
  avatar?: (number | null) | Media;
  /**
   * Краткое описание специалиста для страницы профиля (2–5 предложений).
   */
  bio?: string | null;
  /**
   * Короткая фраза или профессиональный принцип, отображается в Folk-стиле.
   */
  quote?: string | null;
  /**
   * Технологии и инструменты специалиста
   */
  skills?:
    | {
        skill?: string | null;
        id?: string | null;
      }[]
    | null;
  yearsExperience?: number | null;
  projectsDone?: number | null;
  /**
   * Без @, например: ivan_orlov
   */
  telegram?: string | null;
  github?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  hero: {
    headline: string;
    subheadline?: string | null;
    description?: string | null;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  featured?: boolean | null;
  status?: ('in-progress' | 'completed' | 'on-hold') | null;
  thumbnail?: (number | null) | Media;
  shortDescription: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  technologies?:
    | {
        name: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  links?: {
    demo?: string | null;
    github?: string | null;
    figma?: string | null;
  };
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  completionDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  name: string;
  category: 'frontend' | 'backend' | 'database' | 'devops' | 'design' | 'mobile' | 'other';
  proficiency: number;
  icon?: string | null;
  description?: string | null;
  order?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  tags?:
    | {
        tag?:
          | (
              | 'React'
              | 'Next.js'
              | 'TypeScript'
              | 'JavaScript'
              | 'CSS'
              | 'HTML'
              | 'Tailwind CSS'
              | 'Chakra UI'
              | 'Node.js'
              | 'Express'
              | 'MongoDB'
              | 'PostgreSQL'
              | 'Payload CMS'
              | '1С-Битрикс'
              | 'Laravel'
              | 'PHP'
              | 'DevOps'
              | 'Docker'
              | 'Git'
              | 'Web Development'
              | 'Frontend'
              | 'Backend'
              | 'Full Stack'
              | 'UI/UX'
              | 'Design'
              | 'Tutorial'
              | 'Tips'
              | 'Best Practices'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Управление пунктами главного меню навигации сайта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Текст, который отображается в меню
   */
  label: string;
  /**
   * URL или путь, например: /blog, /about, /services
   */
  href: string;
  /**
   * Меньше = левее в меню
   */
  order?: number | null;
  /**
   * Открывать в новой вкладке
   */
  isExternal?: boolean | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Заявки, оставленные через форму на сайте.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  /**
   * Email, телефон или Telegram для связи
   */
  contact: string;
  message?: string | null;
  status?: ('new' | 'processed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Пользователи, подписанные на уведомления о заявках через Telegram-бота.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tg-subscribers".
 */
export interface TgSubscriber {
  id: number;
  chatId: string;
  username?: string | null;
  firstName?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * например: ecommerce-1c-bitrix
   */
  slug: string;
  /**
   * Определяет какой компонент отрендерит страницу
   */
  template: 'ecommerce-bitrix' | 'bitrix24-portal' | 'laravel' | 'devops';
  excerpt?: string | null;
  /**
   * Отображается на карточке главной страницы
   */
  startingPrice?: string | null;
  /**
   * Отображается на карточке главной страницы
   */
  timeframe?: string | null;
  tags?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  content?: string | null;
  status?: ('published' | 'draft') | null;
  hero?: {
    badge?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    description?: string | null;
    stats?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  features?:
    | {
        title?: string | null;
        description?: string | null;
        icon?:
          | (
              | 'ShoppingCart'
              | 'CreditCard'
              | 'Truck'
              | 'Package'
              | 'BarChart'
              | 'Zap'
              | 'Shield'
              | 'Users'
              | 'Settings'
              | 'Server'
              | 'Code'
              | 'Database'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  workStages?:
    | {
        title?: string | null;
        desc?: string | null;
        id?: string | null;
      }[]
    | null;
  prices?:
    | {
        name?: string | null;
        price?: string | null;
        term?: string | null;
        popular?: boolean | null;
        features?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  includedInPrice?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'tg-subscribers';
        value: number | TgSubscriber;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isPublic?: T;
  role?: T;
  position?: T;
  craft?: T;
  avatar?: T;
  bio?: T;
  quote?: T;
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  yearsExperience?: T;
  projectsDone?: T;
  telegram?: T;
  github?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        description?: T;
      };
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featured?: T;
  status?: T;
  thumbnail?: T;
  shortDescription?: T;
  description?: T;
  technologies?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  links?:
    | T
    | {
        demo?: T;
        github?: T;
        figma?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  completionDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  proficiency?: T;
  icon?: T;
  description?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  publishedAt?: T;
  status?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  label?: T;
  href?: T;
  order?: T;
  isExternal?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tg-subscribers_select".
 */
export interface TgSubscribersSelect<T extends boolean = true> {
  chatId?: T;
  username?: T;
  firstName?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  template?: T;
  excerpt?: T;
  startingPrice?: T;
  timeframe?: T;
  tags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  content?: T;
  status?: T;
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  workStages?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  prices?:
    | T
    | {
        name?: T;
        price?: T;
        term?: T;
        popular?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  includedInPrice?:
    | T
    | {
        text?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Управление контентом страницы /team
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-page".
 */
export interface TeamPage {
  id: number;
  /**
   * Первая часть заголовка (обычный текст)
   */
  heroHeading?: string | null;
  /**
   * Курсив crimson-цветом
   */
  heroHeadingAccent?: string | null;
  heroDescription?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  historyHeading?: string | null;
  historyParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        year: string;
        event: string;
        id?: string | null;
      }[]
    | null;
  valuesHeading?: string | null;
  valuesSubtitle?: string | null;
  values?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  showCta?: boolean | null;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  ctaEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Управление контентом главной страницы /
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Например: «Студия цифрового мастерства · с 2012 года»
   */
  heroSupTitle?: string | null;
  heroDescription?: string | null;
  /**
   * Строка «12 лет ремесла • 240+ проектов • 38 мастеров»
   */
  heroStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        target: number;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  manifestoQuote?: string | null;
  manifestoAuthor?: string | null;
  whyUs?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  pricing?:
    | {
        name: string;
        desc: string;
        price: string;
        featured?: boolean | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Управление содержимым подвала сайта
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  brandDescription?: string | null;
  servicesLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  companyLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contactEmail?: string | null;
  contactHours?: string | null;
  copyrightText?: string | null;
  copyrightNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-page_select".
 */
export interface TeamPageSelect<T extends boolean = true> {
  heroHeading?: T;
  heroHeadingAccent?: T;
  heroDescription?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  historyHeading?: T;
  historyParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        year?: T;
        event?: T;
        id?: T;
      };
  valuesHeading?: T;
  valuesSubtitle?: T;
  values?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  showCta?: T;
  ctaHeading?: T;
  ctaDescription?: T;
  ctaEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroSupTitle?: T;
  heroDescription?: T;
  heroStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        target?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  manifestoQuote?: T;
  manifestoAuthor?: T;
  whyUs?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        name?: T;
        desc?: T;
        price?: T;
        featured?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  ctaHeading?: T;
  ctaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandDescription?: T;
  servicesLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  companyLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contactEmail?: T;
  contactHours?: T;
  copyrightText?: T;
  copyrightNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}